config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end
  
  scope'(:locale)' do
  
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  get 'store/help'
  get 'store/about'
   get 'store/news'
  

  
    
  root 'store#index', as: 'store', via: :all
end

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START:i18n -->
  <div id="banner">
<!-- START_HIGHLIGHT -->
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
<!-- END_HIGHLIGHT -->
    
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
<!-- END:i18n -->
  <div id="columns">
    <div id="side">
      <!-- START:hidden_div -->
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>

<!-- END_HIGHLIGHT -->
      
      <ul class="nav nav-pills nav-stacked">
        <li><button type="button" class="btn btn-warning"><a href="/store/index"><%=	t('.home') %></a></button></li>
        <li><button type="button" class="btn btn-warning"><a href="/store/help"><%=	t('.questions') %></a></button></li>
        <li><button type="button" class="btn btn-warning"><a href="/store/news"><%=	t('.news') %></a></button></li>
        <li><button type="button" class="btn btn-warning"><a href="/store/about"><%=	t('.contact') %></a></button></li>
        <li><button type="button" class="btn btn-success"><a href="/users/login"><%=	"Login" %></a></button></li>
      </ul>
      
      <% if session[:user_id] %>
<!-- DROP DOWN BEGIN -->

  <ul class="nav nav-pills nav-stacked">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin Account <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><button type="button" class="btn btn-warning"><%= link_to 'Orders',   orders_path   %></button></li>
          <li><button type="button" class="btn btn-warning"><%= link_to 'Products', products_path %></button></li>
          <li><button type="button" class="btn btn-warning"><%= link_to 'Users',    users_path    %></button></li>
           <li><button type="button" class="btn btn-warning"><%= link_to 'Carts',    carts_path    %></button></li>
           <li><button type="button" class="btn btn-warning"><%= link_to 'Logout', logout_path, method: :delete   %></button></li>
      </ul>
    </li>
  </ul>


<!-- Drop Down end-->
      <% end %>
      
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>